// nm_cache_core.h — L1 in-memory navmesh cache + stats reporter (Layer 3)
// Depends on: nm_cache_types.h, nm_cache_slot_policy.h

#ifndef KENSHI_ZONE_OPT_NM_CACHE_CORE_H
#define KENSHI_ZONE_OPT_NM_CACHE_CORE_H

#include "navmesh/cache/nm_cache_types.h"
#include "navmesh/cache/nm_cache_slot_policy.h"


// Critical sections (shared across navmesh cache modules)
extern CRITICAL_SECTION nmCacheCS;
extern CRITICAL_SECTION processJobCS;
extern CRITICAL_SECTION buildCollisionCS;
extern volatile long    nmCacheDisabled;

// Diagnostic counters (written by bg threads via Interlocked, read by main thread)
extern volatile long nmJobCount;
extern volatile long nmCacheHitCount;
extern volatile long nmCacheMissCount;
extern volatile long nmCacheSkipCount;
extern volatile long nmTotalMsTimes10;
extern volatile long nmSavedMsTimes10;
extern volatile long nmDiagLastGridX;
extern volatile long nmDiagLastGridY;
extern volatile long nmDiagLastType;
extern volatile long nmDiagStep;
extern volatile long nmDiagHitGrid;

// Settings probe buffers (written once by bg thread, dumped by stats reporter)
extern volatile long  nmSettingsDumped;
extern volatile long  nmSettingsVerified;
extern volatile float probeEMP[14];
extern volatile float probeGen[24];
extern volatile float probeMisc[8];
extern volatile float verifyEMP[7];

// WorkBuffer probe state
extern volatile long wbProbeDone;
extern volatile long probeWBPtrLo, probeWBPtrHi;
extern volatile long probeHavokPtrLo, probeHavokPtrHi;
extern volatile long probeWBMatch;
extern volatile long probeNMGPtrLo, probeNMGPtrHi;
extern volatile long probeWBMsize, probeWBHeapSize, probeWBFieldScan;

// hkArray scanner results
extern volatile long wbArrayScanDone;
extern int           wbArrayOffsets[WB_MAX_ARRAYS];
extern volatile long wbArrayCount;
extern int           wbWritableOffsets[WB_MAX_ARRAYS];
extern volatile long wbWritableCount;
extern WBArrayProbe  wbArrayProbes[WB_MAX_ARRAYS];
extern int           wbSdkArrayOffsets[WB_MAX_SDK_ARRAYS];
extern int           wbSdkArrayCount;

// L2 disk cache counters
extern volatile long nmDiskHitCount;
extern volatile long nmDiskMissCount;
extern volatile long nmDiskWriteCount;
extern volatile long nmDiskReadUsTimes1;
extern volatile long nmDiskWriteUsTimes1;

// L2 miss log
extern L2MissEntry   l2MissLog[L2_MISS_LOG_MAX];
extern volatile long l2MissLogCount;
extern volatile long l2MissLogReported;

// Worker counters (defined here, written by workers via Interlocked, read by stats reporter)
extern volatile long workerBusyCount;
// A busy-bridge transition that ended, under the queue lock, with the byte 0
// while a claim was in flight. Reported as busyViol= (DEV); expected 0.
extern volatile long nmBusyBridgeViolCount;
extern volatile long g_slabAllocHits;
extern volatile long g_slabAllocWorkerHits;

// WorkBuffer clone size (set by the work buffer probe, read by workers/dispatch)
extern volatile long g_workBufAllocSize;

// Lazy hook install marker (0=pending, 1=installing, 2=done) for the hooks
// InstallNavMeshLazyHooks puts in on the first dispatch: the edgeProcess
// clone-guard, the populate pass-through and the processJobAlt tripwire.
extern volatile long lazyHooksInstalled;

// Per-MISS NMG clone counters
extern volatile long nmCloneConstructCount;      // successful clone allocations
extern volatile long nmCloneConstructFailCount;  // HavokTlsAlloc returned NULL

// Worker vs bg thread MISS split. Sum should equal nmCacheMissCount.
extern volatile long nmWorkerMissCount;          // MISSes processed by workers
extern volatile long nmBgMissCount;              // MISSes processed by bg thread

// Duplicate jobs: L1 re-check under processJobCS found the key already generated by
// another thread (counted in nmCacheHitCount as well).
extern volatile long nmLateHitCount;

// edgeProcess clone-guard diagnostics. "armed" = guard skipped cleanup on a
// clone-context entry (safe). "unarmed" = guard forwarded to original (must be realWB
// or game-owned — otherwise crash risk). Divergence from expected = guard misbehavior.
extern volatile long g_edgeProcessArmedCount;
extern volatile long g_edgeProcessUnarmedCount;

// Material overrides on fresh work buffers. wbOv= reports the count
// left in the +520 array after processJobAlt's finalizeDeep popped the entry
// the job appended; 4 is correct. wbOvSlope= counts entries where the slope in
// NM_MATERIAL_SLOPE_BITS disagreed with the one the game installed.
extern volatile long g_wbOverrideInstalled;
extern volatile long g_wbOverrideAfterPop;
extern volatile long g_wbOverrideSlopeBad;
// Teardown found more entries than ConstructFreshSettings can have appended, so
// it left them alone. Reported as wbOvSkip= only when non-zero; expected 0.
extern volatile long g_wbOverrideSkipped;

// wb+328 (m_minCharacterWidth) on the last fresh work buffer, held as the raw
// float bits. Reported as wbQ=; 0.90 is the game's own value, copied from the
// real work buffer.
extern volatile long g_wbQualityLast;

// Fresh-WB pruning proof token (nm_quality.h). The region-pruning scalars of the
// session's first fresh work buffer, as read from it after
// ConstructFreshSettings' copies, latched once (g_wbPruneSeen 0 -> 1 claimed ->
// 2 once the four values are stored). Reported on every stats line as
// prune=<on|off>(area=..,seed=..,border=..,pvb=..,pbt=..): on = navmeshVanillaPruning; the values read 1e8/0.40/0.00 with it on and
// Havok's 5/1.00/0.10 with it off. Written on the NavMesh bg thread or a worker
// (Interlocked only), read by the main-thread stats reporter.
extern volatile long g_wbPruneSeen;
extern volatile long g_wbPruneAreaBits;
extern volatile long g_wbPruneSeedBits;
extern volatile long g_wbPruneBorderBits;
extern volatile long g_wbPruneFlags;         // pvb | pbt << 8
// Fresh work buffers built with a copied block (the real WB's actual bytes)
// that differs from the nm_quality.h table the L2 settings hash describes
// (pruneBad= / xvBad=, printed only when non-zero; expected absent). Any such
// difference also turns L2 off for the session (g_l2Bypass below).
extern volatile long g_wbPruneBad;
extern volatile long g_wbExtraVertexBad;

// L2 bypass. Set once, never cleared, when the real work
// buffer's region-pruning or extra-vertex values differ from the tables the
// settings hash describes: meshes generated from then on would not match their
// cache key, so ReadDiskCache and BuildDiskCacheBlob refuse every read and
// write for the rest of the session. L1 stays on (per session, generated with
// the same values). Checked at the first dispatch (CheckGenerationSettingsKey,
// nm_quality.h) and again on every fresh work buffer. Reported as
// l2Bypass=on(r<reads>/w<writes>) when set, and by one PROD line
// "NavMesh L2 bypassed: generation settings differ from the cache key (...)".
extern volatile long g_l2Bypass;
extern volatile long nmL2BypassReads;
extern volatile long nmL2BypassWrites;
inline bool L2Bypassed() { return InterlockedCompareExchange(&g_l2Bypass, 0, 0) != 0; }

// True when the
// getSeedPointsFromAdjacentZone hook is wanted: not turned off in the INI. Read-only after LoadConfig, any thread.
inline bool NmNbrSeedHookWanted()
{
	return navmeshNeighbourSeedsEnabled;
}

// The hook's install state: 0 not tried yet (before the first dispatch),
// 1 installed, 2 refused (prologue mismatch or AddHook failure). A refusal turns
// the whole feature off for the session. Written once by
// InstallNavMeshLazyHooks on the NavMesh bg thread, read anywhere.
extern volatile long g_nbrSeedHookState;

// Every call of the hooked getSeedPointsFromAdjacentZone, one per direction of
// a type-0 generation, classified after the original ran. Disjoint:
//   live  the original appended seeds (a live or completed neighbour mesh)
//   zero  no seeds, but a live non-temp neighbour sector exists (it has no
//         border edge on that side: cliff, water, or a town placeholder)
//   temp  no seeds; the neighbour sector is temp (a stale tile awaiting
//         regeneration, which the game refuses as a seed source)
//   none  no seeds; no neighbour sector at all (unloaded)
// Reported as nbrSeed=live<n>/temp<n>/none<n>/zero<n>. Interlocked only.
extern volatile long nmNbrSeedLive;
extern volatile long nmNbrSeedTemp;
extern volatile long nmNbrSeedNone;
extern volatile long nmNbrSeedZero;

// Set once when a stand-in callee fails its byte check (SortedArray__grow, the
// game's string release) or the hkContainerHeapAllocator vtable differs: the
// stand-in is off for the session (the hook's instrumentation stays).
extern volatile long g_nbrSeedStandInRefused;

// Stand-in outcomes, one per call where the game added nothing and the neighbour
// was temp or missing (only on type-0 generations the mod runs):
//   ship    the shipped tile's seeds for that side were appended
//   place   the shipped tile gives nothing there: a placeholder (< 1000 faces,
//           or no border-strip edge on any side) or no border-strip edge on
//           this side
//   nofile  no shipped tile (outside the 64x64 grid, or no file)
//   late    the tile's record was not built yet (another thread still loading
//           it past the bounded wait, the prefetch skipped for the stop, or the
//           neighbour turned missing or temp after the prefetch saw it live)
// Reported as standIn=ship<n>/place<n>/nofile<n>/late<n>, siSeeds=<avg seeds
// per ship>, siMs=<avg>/<max> over the shipped-tile loads (lock wait, load,
// extraction, delete), siRec=<records built>; siHBad=<n> (a record built with
// another strip width than the target's; expected absent) only when non-zero.
extern volatile long     nmNbrStandInShip;
extern volatile long     nmNbrStandInPlace;
extern volatile long     nmNbrStandInNoFile;
extern volatile long     nmNbrStandInLate;
extern volatile long     nmNbrStandInHBad;
extern volatile LONGLONG nmNbrStandInSeeds;
extern volatile long     nmNbrLoadCount;
extern volatile LONGLONG nmNbrLoadTotalUs;
extern volatile long     nmNbrLoadMaxUs;
extern volatile long     nmNbrRecordCount;
// Generations with a late stand-in whose mesh was kept out of
// L2 (the L1 entry stays). Printed as l2LateSkip=<n> right after standIn=.
extern volatile long     nmNbrL2LateSkip;

// True when the stand-in seeds are wanted in the INI, and neither the hook nor a callee check refused them. Decides the
// L2 settings hash ("nbrseed1"). Before the first dispatch (hook state 0) it
// answers for the install that is about to happen; a refusal there flips it
// before any L2 file is read or written (every L2 access runs on a NavMesh
// thread after InstallNavMeshLazyHooks). Any thread.
inline bool NmNbrSeedStandInActive()
{
	return navmeshNeighbourSeedsEnabled
	    && InterlockedCompareExchange(&g_nbrSeedHookState, 0, 0) != 2
	    && InterlockedCompareExchange(&g_nbrSeedStandInRefused, 0, 0) == 0;
}

// Type-1 (partial) jobs whose partialGeneration call was made against the real
// generator rather than a worker's clone. Reported as nbrLookup=.
extern volatile long nmPartialRealCount;

// processJobAlt called by a thread that did not own processJobCS. Reported as
// trip=; expected 0 over a whole session.
extern volatile long nmTripCount;
// 0 until the tripwire hook is installed. trip= prints "off" while it is 0,
// because no violations counted is not the same as none possible.
extern volatile long nmTripInstalled;

// Time spent inside orig_dispatchJob under processJobCS for type 2/3/4 jobs,
// in tenths of a millisecond. Reported as t234=<avg>/<max>ms.
extern volatile long nmT234Count;
extern volatile long nmT234TotalMsTimes10;
extern volatile long nmT234MaxMsTimes10;

// Entries into a collision-build region (either hooked builder, or the
// partialGeneration call) that found another region already in flight, i.e.
// build regions in flight > 1. Reported as bcOverlap=.
//
// NOT "races prevented": two threads can both be in a build region and still
// be serialized by the game's own build mutex inside buildSectionCollision.
// What this counts is concurrency at the region level, which is the necessary
// condition for the unguarded tail races, not proof one occurred.
extern volatile long g_buildOverlapSeen;

// buildCollisionCS wait (blocked in Enter) and hold (Enter to Leave) across all
// three regions. Totals are 64-bit microseconds; the maxima are microseconds.
// Reported as bcWait=<avg>/<max>ms bcHold=<avg>/<max>ms.
extern volatile long     nmBcCount;
extern volatile LONGLONG nmBcWaitTotalUs;
extern volatile long     nmBcWaitMaxUs;
extern volatile LONGLONG nmBcHoldTotalUs;
extern volatile long     nmBcHoldMaxUs;

// Semaphore handles closed when a worker's NMG clone is freed
// (15 per clone), and handles skipped because they were still identical to the
// real generator's, i.e. never re-created by fn_queueLockInit. hSkip= is
// printed only when non-zero and should never appear.
extern volatile long nmCloneHandleClosed;
extern volatile long nmCloneHandleSkipped;

// Bytes released per fresh-work-buffer teardown (the +520 guard,
// the +288 material-map copy and the 544-byte block). DEV only, reported as
// wbFreed=. It does NOT include what the dtor body itself frees, which is the
// bulk of it and is not measurable from here.
extern volatile LONGLONG nmWbFreedBytes;

// A worker HIT that could not be served from its slot — the slot no longer held
// the job's key by the time it reconstructed, the index was out of range, or the
// reconstruct itself failed — so the job was regenerated instead of being
// deleted with no mesh. Reported as hitStale=; expected small.
extern volatile long nmHitStaleCount;

// A rebuild from a saved slot index found the index unusable: outside the
// ring, or naming a slot that no longer holds the key with a servable mesh
// (the ring published over it, or the cache was cleared). The job regenerates.
// Reported as l1Replaced=; expected small.
extern volatile long nmL1ReplacedCount;

// L2 file reads skipped because another worker was already reading that exact
// key, which only happens for duplicate jobs on one zone. Reported as dupL2=.
extern volatile long nmDupL2Avoided;

// The in-flight table had no free slot, so the read went ahead unregistered.
// Distinct from dupL2: nobody was reading that key.
extern volatile long nmL2FlightFull;


// A claimed job whose zone the game unloaded while the
// job waited on processJobCS. Ungated: the re-check restores vanilla's own test
// (dispatchJob_orig 0x3CE030 drops a job whose zone has no mapContent), and the
// measurement is this round's. All written on the NavMesh bg thread and the
// workers with Interlocked* only (no allocation, no logging there), read by the
// main-thread stats reporter, cumulative since session start.
//
// processJobCS wait, per acquisition site: time blocked acquiring the lock.
//   PJWAIT_CLONE  — the worker's CloneNMG snapshot lock
//   PJWAIT_WMISS  — missLock in ProcessNavMeshJob on a worker thread
//   PJWAIT_BGMISS — missLock in ProcessNavMeshJob on the NavMesh bg thread
// Reported as pjWait clone=<avg>/<max> wMiss=<avg>/<max> bgMiss=<avg>/<max>ms.
enum PjWaitSite
{
	PJWAIT_CLONE      = 0,
	PJWAIT_WMISS      = 1,
	PJWAIT_BGMISS     = 2,
	PJWAIT_SITE_COUNT = 3
};
extern volatile long     nmPjWaitCount[PJWAIT_SITE_COUNT];
extern volatile LONGLONG nmPjWaitTotalUs[PJWAIT_SITE_COUNT];
extern volatile long     nmPjWaitMaxUs[PJWAIT_SITE_COUNT];

// MISS entries (CloneNMG or missLock) that stood aside because a bounded
// processJobCS poll (NavMeshTryLockProcessJobFor with a timeout, the save-load
// reset) wanted the lock. Their delay is inside the pjWait figures above.
// Reported as pjYield= only when non-zero.
extern volatile long     nmPjYieldCount;

// Mod-unload protocol (nm_workers.h). Cumulative, printed on the stats
// line (DEV and PROD) so a session can see unloads being deferred:
//   ulSkipJob=   NavMeshBeginZoneUnload refused: a job for the zone was queued
//   ulSkipClaim= NavMeshBeginZoneUnload refused: a claim for the zone in flight
//   ulSkipPj=    processJobCS try failed while an unload was published
//   ulHeld=      claim attempts that left the unloading zone's job queued
//                (printed only when non-zero)
//   ulPrio=      unload priority requests raised after a pj deferral
//                (NavMeshRequestPjPriority)
//   ulPrioWin=   zero-wait tries that won while a request was still up
extern volatile long     nmUlSkipJob;
extern volatile long     nmUlSkipClaim;
extern volatile long     nmUlSkipPj;
extern volatile long     nmUlHeld;
extern volatile long     nmUlPrio;
extern volatile long     nmUlPrioWin;

// Claim age: QPC at the job's unlink from the generator queue -> the zone
// re-check. MISS: at the authoritative re-check right after missLock is
// acquired (worker and bg thread). HIT: at the re-check at the top of
// WorkerProcessHit, just before the reconstruct (worker HITs only; the bg
// thread's own HIT path never waits on processJobCS). Reported as
// claimAge miss=<avg>/<max> hit=<avg>/<max>ms and, for MISSes only, the bucket
// counts [<10:a <100:b <1s:c <5s:d >=5s:e].
// A HIT whose slot turned stale (hitStale=) is counted in hit= and
// again in miss= when it regenerates, so hit= + miss= is not a job count.
enum { CLAIMAGE_BUCKET_COUNT = 5 };
extern volatile long     nmClaimAgeMissCount;
extern volatile LONGLONG nmClaimAgeMissTotalUs;
extern volatile long     nmClaimAgeMissMaxUs;
extern volatile long     nmClaimAgeMissBucket[CLAIMAGE_BUCKET_COUNT];
extern volatile long     nmClaimAgeHitCount;
extern volatile LONGLONG nmClaimAgeHitTotalUs;
extern volatile long     nmClaimAgeHitMaxUs;

// Claimed jobs dropped because their zone was unloaded, the way vanilla's early
// return drops them (not freed, not enqueued). Reported as
// stale=w<n>/bg<n>/hit<n>/early<n> staleLast=(x,y)t<type>/<reason>@<ms>ms.
// A job dropped because NavMesh::stop was seen takes the
// same exits with reason shutdown. Those are also counted on the
// worker retire line as stopDrop=, and since no stats line follows
// NavMesh::stop, stale= on the stats line in practice never includes them.
// A job that waited out a save-load reset and lost its zone's content counts
// at its path's site; dropped at a collision build, it is freed, not enqueued.
enum StaleSite
{
	STALE_SITE_WMISS  = 0,   // worker, after missLock
	STALE_SITE_BGMISS = 1,   // bg thread, after missLock
	// a HIT dropped for an unloaded zone: a worker's before the rebuild, any
	// thread's after a reset wait
	STALE_SITE_HIT    = 2,
	STALE_SITE_EARLY  = 3,   // worker MISS, before CloneNMG
	STALE_SITE_COUNT  = 4
};
enum StaleReason
{
	STALE_REASON_NONE       = 0,
	STALE_REASON_NO_ZONE    = 1,   // job+0 (ZoneMap*) is NULL
	STALE_REASON_NO_CONTENT = 2,   // ZoneMap+0 (mapContent) is NULL
	STALE_REASON_NO_TERRAIN = 3,   // ZoneMap+0xB8 (terrainCollision) is NULL
	STALE_REASON_SHUTDOWN   = 4    // NavMesh::stop seen (also stopDrop=)
};
extern volatile long nmStaleCount[STALE_SITE_COUNT];
// The last drop, as five plain volatile LONGs each written on its own (no lock
// ties them together): a reader racing two drops can see fields from both (a
// torn read), which is acceptable for a diagnostic that only reports the most
// recent event.
extern volatile long nmStaleLastGridX;
extern volatile long nmStaleLastGridY;
extern volatile long nmStaleLastType;
extern volatile long nmStaleLastReason;
extern volatile long nmStaleLastAgeUs;

// Workers that completed Havok thread init and have not exited. Reported as
// workers=<live>.
extern volatile long g_navMeshWorkersLive;

// The worker pool's refusal for the session, an NmPoolDecision; 0 while the
// pool is allowed or not yet decided. Set once on the NavMesh bg thread; a
// refusal prints workers=<its token> in place of the live count.
extern volatile long g_navMeshPoolRefusal;

// L2 rejection counters, one per L2RejectReason, and the size-cap eviction count
extern volatile long l2RejCount[L2REJ_REASON_COUNT];
extern volatile long l2CapEvicted;

// L2 writes refused because the entry had zero faces
// (BuildDiskCacheBlob). Reported as l2ZeroSkip= only when
// non-zero; expected absent, since L1 already refuses zero-face meshes.
extern volatile long nmL2ZeroFaceSkip;

// ReconstructNavMesh gave up on a Havok allocation failure and freed everything
// it had taken. Reported as reconFail= on the stats line.
extern volatile long nmReconFailCount;

// Meshes that came back with zero faces, whether freshly generated or read out
// of an old L2 file. A generation that aborts (a Havok keycode, out of memory)
// is indistinguishable from a legitimately empty tile at this level, and
// caching one makes that tile permanently empty, so none of
// them are stored or served. Reported as zeroFace= on the stats line.
extern volatile long nmZeroFaceCount;
extern volatile long nmZeroFaceLastTri;
extern volatile long nmZeroFaceLastVert;
extern volatile long nmZeroFaceLastThings;
extern volatile long nmZeroFaceLastGridX;
extern volatile long nmZeroFaceLastGridY;
extern volatile long nmZeroFaceLastType;

// The split the L2 rule is decided on: zero faces out of an empty input is
// a legitimately empty tile, zero faces out of a real input is an aborted
// generation. Reported as zfEmptyIn= and zfAbort=.
extern volatile long nmZeroFaceEmptyInput;
extern volatile long nmZeroFaceAbort;

// Records one zero-face mesh. inputTri is the generation's input triangle
// count, captured by the populate hook (-1 when it is unknown, e.g. a mesh read
// back from an L2 file); inputThings is the zone's things count, or -1.
// Safe on any thread.
void NoteZeroFaceMesh(const NavMeshCacheKey& key, int inputTri, int inputVert, int inputThings);

// Disk cache directory (initialized by InitNavMeshCacheCS, used by nm_disk_cache).
// nmDiskCacheDirBuf is the char copy the bg threads use — no CRT string objects
// off the main thread. Both end with a trailing backslash.
extern std::string   nmDiskCacheDir;
extern char          nmDiskCacheDirBuf[MAX_PATH];
extern bool          nmDiskCacheDirChecked;


// L1 ring buffer state (shared with nm_workers for ProcessNavMeshJob access)
extern NavMeshCacheEntry nmCache[NM_CACHE_SIZE];
extern int               nmCacheWriteIdx;
extern int               nmCacheFill;
extern int               nmDiagStage;

// Cache operations
void           InitNavMeshCacheCS();
void           ClearNavMeshCache();
int            FindCacheEntry(const NavMeshCacheKey& key);
void           EvictCacheEntry(int idx);
// Deep-copies the generated mesh into the ring buffer. Returns the slot index,
// or -1 when the mesh is out of bounds or an allocation failed (nothing is
// stored in that case — never a valid entry with a NULL array).
// Caller must hold nmCacheCS.
int            StoreCacheEntry(const NavMeshCacheKey& key, uintptr_t navMeshPtr);

// Moves a freshly read L2 entry into the ring buffer and returns its slot
// index, or -1 (the entry's arrays are freed) when it is inconsistent.
// Takes ownership of `e` on success. Caller must hold nmCacheCS.
int            PromoteDiskEntryToL1(NavMeshCacheEntry& e);
void*          ReconstructNavMesh(const NavMeshCacheEntry& entry);
// Rebuilds the mesh of slot idx, an index taken under an earlier nmCacheCS
// hold, only if the slot still holds `expected` (CacheSlotMatches). Caller
// holds nmCacheCS. NULL when idx no longer names a servable slot for
// `expected` (out of range, another key or no faces; *replacedOut true,
// counted l1Replaced=) or the rebuild failed (*replacedOut false).
// replacedOut may be NULL.
void*          ReconstructExpected(const NavMeshCacheKey& expected, int idx, bool* replacedOut);
unsigned int   HashAABB(const float* aabb6);

// --------------------------------------------------------------------
// Claim-time content reads
// --------------------------------------------------------------------
//
// The building hash walks the zone content's things list (content+0x60,
// count +0x58) on the NavMesh bg thread and the workers, at claim time, with no
// lock the main thread respects. The game's own unload runs on the main thread:
// ZoneMapContent::deactivate (0x9FDAB0) first destroys every thing through
// GameWorld::destroy_RootObject and zeroes the count (0x9FDEC3-0x9FDF05), then
// the content is deleted, and only then is ZoneMap::mapContent (zone+0) NULLed.
// A walk that overlaps any of that reads freed memory or a list being rewritten.
//
// So the walk runs under SEH (GuardEnter/GuardLeave, POD-only function) and
// checks itself: zone+0, the things count and the things buffer are read before
// and after it. It is trusted only when nothing faulted, the content is
// non-NULL and all three are unchanged. An untrusted hash keys nothing: the job
// is neither looked up in nor stored to L1 or L2 (so a wrong mesh can neither
// be served nor published); it is still generated, or dropped by the stale-zone
// re-check.
//
// hashRace= on the NM cache stats line counts every refusal: a hash that failed
// its own check, and a store whose zone no longer held the content the hash was
// computed from (ZoneContentUnchanged, below). One job can count twice (the
// worker's claim-time lookup and ProcessNavMeshJob hash independently).
extern volatile long nmHashRaceCount;

// Computes the order-independent building hash (see nm_building_hash.cpp) for the
// zone's current content. Returns true when the hash is trustworthy; *hashOut is
// the hash and *contentOut the content pointer it was computed from. Returns
// false (counted as hashRace=) when the walk faulted, the content was NULL, or
// the content / things count / things buffer changed during the walk; *hashOut
// and *contentOut are then 0 and the key must not be used for L1 or L2.
// Any thread; no allocation, no logging.
bool           ComputeBuildingHashChecked(uintptr_t jobZone, unsigned int* hashOut,
                                          uintptr_t* contentOut);

// True when the zone's mapContent is still `content` (and non-NULL). A plain
// read of zone+0: ZoneMap entries live in the ZoneManager's fixed array and are
// never freed. Used right before an L1 store, so a mesh keyed on content that
// has since been unloaded (or unloaded and reloaded) is never published.
bool           ZoneContentUnchanged(uintptr_t jobZone, uintptr_t content);

// The zone content's things count for diagnostics (the L2-miss log, the
// zero-face record), read under SEH. -1 when the content is NULL or the read
// faulted. Any thread.
int            SafeZoneThingsCount(uintptr_t jobZone);

// Stats reporter (called from main thread)
void LogNavMeshCacheStats(double now);


#endif // KENSHI_ZONE_OPT_NM_CACHE_CORE_H
